### ISSUE TITLE
I can't compile the program

### ISSUE THREAD

**Issue by vicivanruiz** [Espressobar/arduino_grind_timer#1]
Hello @zrrbite , I tried to verify this program and it shows me a problem with the Wire.h library this is the error that appears: In file included from /Users/Ivan/Desktop/arduino-grind-timer-master/src/Grinder_Timer_1_1/Grinder_Timer_1_1.ino:20:0:
/Users/Ivan/Documents/Arduino/libraries/DigoleSerial/DigoleSerial.h:7:26: fatal error: ../Wire/Wire.h: No such file or directory
 #include "../Wire/Wire.h"

Do you know what could be wrong? 

PD. I tried to modify the DigoleSerial.h in the line 7 #include "../Wire/Wire.h" to #include "Wire.h" but the problem stills

**Comment by zrrbite** [comment]
Hi vicivanruiz,

Since you closed this, did you resolve the issue?

**Comment by vicivanruiz** [comment]
Hi, yes I replace the "../Wire/Wire.h" to #include "Wire.h" in the DigoleSerial.h and this time works perfectly! Now I'm waiting for the OLED screen to arrive to finally test the circuit! 

Regards!!
